### ISSUE TITLE
When running a LAN server, users cannot join unless they have Lighty installed

### ISSUE THREAD

**Issue by 31j** [SchmarrnDevs/Lighty#23]
As the title says users who try to join the server cannot unless they also have the mod installed. This extends to lan servers proxied through e4mc although I did try disabling that mod just in case. 

Fabric 0.14.21 | Minecraft 1.20 
Lighty 2.00 for MC 1.20 
Prism Launcher Flatpak on Fedora Linux

**Comment by andi-makes** [comment]
Does this also happen for other client-only mods? Just checking if this is a general issue with all client side mods or just with lighty

**Comment by 31j** [comment]
I have only had the issue with controlify as well, otherwise all of the other mods I use client side (just performance / optifine parity) do not have issues

**Comment by andi-makes** [comment]
Thank you for reporting this issue, a friend of mine found the potential culprit of this bug (Lighty registers blocks only on the client side for rendering carpet mode, and those try to get synced).

A fix for that was already planned, can't give a timeframe in which it will be fixed though, because I don't have time right now.

Depending if you trust me and a random jar from my computer (last time I checked I wasn't infected by [fractureiser](https://github.com/fractureiser-investigation/fractureiser)), you can try this lighty build. I just disabled carpet mode, which should "fix" this issue, a real fix will come at a later point as a real release:
[lighty-2.0.0-no-carpet+1.20.zip](https://github.com/SchmarrnDevs/Lighty/files/11739168/lighty-2.0.0-no-carpet%2B1.20.zip)

According to [this online scanner linked in the fractureiser repo](https://douira.github.io/fractureiser-web-detector/), this jar should be clean from the malware, but feel free to check using other means.

If you decide that you want to use the jar, please tell me if it fixed the problem. Then I can rest assured that my planned fix will probably work

**Comment by andi-makes** [comment]
Should be fixed now, [find the new version on Modrinth](https://modrinth.com/mod/lighty/version/v2.0.1+1.20.1).

Feel free to re-open if the issue still exists
