### ISSUE TITLE
Add option to only shown spawnable

### ISSUE THREAD

**Issue by p3lim** [SchmarrnDevs/Lighty#41]
Basically hiding the green overlays, only showing red/orange.

**Comment by andi-makes** [comment]
Thank you for your suggestion, I'll look into it! May take some time though

**Comment by andi-makes** [comment]
Fixed with Lighty v2.1.0, which you can find [on Modrinth](https://modrinth.com/mod/lighty/versions) or [on GitHub](https://github.com/SchmarrnDevs/Lighty/releases/tag/v2.1.0%2B1.20.1).

There are also some other goodies in this release, so feel free to check it out!

Thanks for opening this issue, have fun playing!
