### ISSUE TITLE
Add support for carpet overlay opacity

### ISSUE THREAD

**Issue by Reava** [SchmarrnDevs/Lighty#46]
Due to how it is, the overlay appears really bright with some shaders, like, REALLY bright, adding opacity or some sort of control of the carpet overlay's display would help resolve this.

![2023-08-28_10 38 51](https://github.com/SchmarrnDevs/Lighty/assets/93742413/a37f0c58-201a-4ef5-9d2c-3e040b0c1ff5)

**Comment by andi-makes** [comment]
Thank you for reporting this issue!

Theoretically, the carpet overlay is already translucent without shaders, weird that it isn't with shaders.

I'll look into it, but it might take some while until I have time to tackle this issue

**Comment by andi-makes** [comment]
Fixed with Lighty v2.1.0, which you can find [on Modrinth](https://modrinth.com/mod/lighty/versions) or [on GitHub](https://github.com/SchmarrnDevs/Lighty/releases/tag/v2.1.0%2B1.20.1).

You cannot change the opacity, as this would be quite difficult to do, but you can change the brightness of the overlay in the Lighty Settings. There are also some other goodies in this release, so feel free to check it out!

Thanks for opening this issue, have fun playing!
