### ISSUE TITLE
[Back-Port] Show Safe to 1.19.4

### ISSUE THREAD

**Issue by h3oCharles** [SchmarrnDevs/Lighty#60]
when looking around an already-lit area and looking for blind spots, I don't need to see that the area around me is lit

(idk if this is relevant, but I'm using v1.3.1+1.19.4 cuz the SMP I'm playing in has limited itself to that mc version)

**Comment by andi-makes** [comment]
Thanks for your suggestion!

This feature has been implemented in Lighty already, but for later Minecraft versions (Lighty v2.1.0 and up, available for Minecraft 1.20.1 and later).

Because v1.3.1+1.19.4 is quite old and there have been major changes to how Lighty works between that version and the version the feature was implemented, I won't back-port the feature because of limited time on my end. I am, however, open to PRs that back-port the feature from v2.1.0 to v1.3.1.

I hope you understand. Thank you for using Lighty!

**Comment by andi-makes** [comment]
I did create a new open meta-issue referencing this one, so this is a little bit more discoverable than just a closed issue. That way, if someone else wants to work on it, they can find this issue more easily.
