### ISSUE TITLE
Overlay not Rotating with Camera

### ISSUE THREAD

**Issue by stormjacque44** [SchmarrnDevs/Lighty#62]
I am having a bug where the overlay is remaining fixed in the camera view despite the camera rotating.
![2024-05-30_12 58 41](https://github.com/SchmarrnDevs/Lighty/assets/9771212/893a4dad-fb71-422f-bdd7-ff634ef20e7b)
![2024-05-30_12 58 41](https://github.com/SchmarrnDevs/Lighty/assets/9771212/299a8506-ab0c-4e34-90d6-5de84e8eadde)
![2024-05-30_12 58 47](https://github.com/SchmarrnDevs/Lighty/assets/9771212/c4782616-6522-4502-94ac-a271491b4de6)
![2024-05-30_12 58 47](https://github.com/SchmarrnDevs/Lighty/assets/9771212/ca4acda1-1fb1-42d9-b3ea-6e0560d0ba4b)
![2024-05-30_12 58 53](https://github.com/SchmarrnDevs/Lighty/assets/9771212/81155fa9-3dd5-45ce-9bcd-0f7ae32d1c5a)
![2024-05-30_12 58 36](https://github.com/SchmarrnDevs/Lighty/assets/9771212/b3053b79-06dc-4313-8d32-67009e64473a)
![2024-05-30_12 58 36](https://github.com/SchmarrnDevs/Lighty/assets/9771212/87a787a7-7f1b-45c2-90ed-78170b6a00fb)
![2024-05-30_12 58 39](https://github.com/SchmarrnDevs/Lighty/assets/9771212/d22af37e-9401-41e9-81ef-5f95555eb45e)
![2024-05-30_12 58 39](https://github.com/SchmarrnDevs/Lighty/assets/9771212/2e25af23-62a4-4d89-9cf5-cf0c46db3d41)

**Comment by andi-makes** [comment]
Thanks for opening this issue!

Please make sure you are using Lighty `v3.0.0-beta.1+1.20.5`. For some reason, CurseForge wrongly suggests Lighty for 1.20.3/4 for versions 1.20.5/6, and I *cannot* change that. Very weird CurseForge bug.

Anyways, it has been fixed in v3.0.0-beta.1, so make sure you use that.

Thanks for using Lighty, and let me know if this fixes the Problem! Have fun!

**Comment by stormjacque44** [comment]
Thank you!
