### ISSUE TITLE
Overlay follows player and moves with head

### ISSUE THREAD

**Issue by ArcherGirlX** [SchmarrnDevs/Lighty#65]
I don't know where to begin with this issue. I play on 1.20.6, at first I thought it was conflicts with other performance mods like Sodium but when I turned on the mod alone, I still had the issue.

If I press F7 and go to overlay settings, the game outright crashes.
Crash log: https://pastebin.pl
Unlisted Video of bug: https://youtu.be/gMJ0CZguox4

**Comment by andi-makes** [comment]
*Slightly adapted from issue #62*

Thanks for opening this issue!

Please make sure you are using Lighty v3.0.0-beta.2+1.20.6. For some reason, CurseForge wrongly suggests Lighty for 1.20.3/4 for versions 1.20.5/6, and I cannot change that. Very weird CurseForge bug.

Anyways, it has been fixed in v3.0.0-beta.2, so make sure you use that.

*end of adapted copy paste from issue #62*

I've marked v3.0.0 as a beta because I haven't finished adding all features I want in Lighty v3.0.0 yet.
Playing on a Lighty beta shouldn't cause any problems, I've taken extra care about that!

As a precaution, I'll leave this issue open and pin it, so that anyone else who encounters this "bug" can find all the relevant information here. If v3.0.0-beta.2 doesn't fix the problem, let me know as well, and I'll look into fixing it.

Thanks for using Lighty, and let me know if updating fixes the Problem! Have fun!

(small note: the link to the crash log is just to the pastebin website, not to the actual crash log itself. But I highly appreciate the intention of providing the crash log, those always proof to be very useful!)
